### ISSUE TITLE
Unnecessary re-drawing

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [zupzup/rust-wgpu-gui-example#3]
I'm running it on Linux. I'm not sure if it's different on the web. The app redraws at 60FPS, when it really only needs to redraw for the cursor to blink, and for handling mouse events. Maybe this was intentional as a way of showing FPS, but I think a good example should not waste resources just to show that it's capable of running at the screen's refresh rate when it's just rendering the same thing over and over.

**Comment by zupzup** [comment]
This project contains example code for a blog post on wgpu, which aims to show how to create a rendering pipeline and how to use it to draw interactive stuff on the screen. (https://zupzup.org/rust-wgpu/)

What this means is that this repository contains code that is kept as brief as possible to make a point and will certainly lack in many areas when viewed through a lens of what would be desirable for production software. That is indeed quite by design, or rather, necessitated by the constraints of the context it was published in.

That said, feel free to fork and extend the code in any way you like, that's what the permissive license is for. :)
